const express = require("express");
const blogController = require("../controllers/blog");
const { decodeToken } = require("../utils/authentication");
const { validateLoggedIn } = require("../utils/authorization");
const router = express.Router();
router.get("/all", blogController.getAllBlogs);
router.get("/:blogId", blogController.getBlogById);
router.get("/", decodeToken, validateLoggedIn, blogController.getOwnBlogs);
router.post("/", decodeToken, validateLoggedIn, blogController.postBlog);
router.post("/:blogId", decodeToken, blogController.postComment);
router.patch("/:blogId", decodeToken, validateLoggedIn, blogController.updateBlog);
router.delete("/:blogId", decodeToken, validateLoggedIn, blogController.deleteBlog);
router.patch("/:blogId/:commentId", decodeToken, validateLoggedIn, blogController.updateComment);
router.delete("/:blogId/:commentId", decodeToken, validateLoggedIn, blogController.deleteComment);
module.exports = router;
