const express = require("express");
const userController = require("../controllers/user");
const { decodeToken } = require("../utils/authentication");
const { validateNotLoggedIn, validateLoggedIn } = require("../utils/authorization");
const router = express.Router();
router.post("/register", decodeToken, validateNotLoggedIn, userController.registerUser);
router.post("/login", decodeToken, validateNotLoggedIn, userController.loginUser);
router.get("/", decodeToken, validateLoggedIn, userController.retrieveUserDetails);
router.patch("/", decodeToken, validateLoggedIn, userController.updateUser);
module.exports = router;
