name: Run Mocha Tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "21.7.1"
            - name: Install dependencies
              run: npm install
            - name: Run Mocha tests
              env:
                  DEMO1_PORT: ${{ secrets.DEMO1_PORT }}
                  DEMO1_MONGO_STRING: ${{ secrets.DEMO1_MONGO_STRING }}
                  DEMO1_JWT_SECRET_KEY: ${{ secrets.DEMO1_JWT_SECRET_KEY }}
              run: npm test
